# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 640)
        self.add = QtWidgets.QPushButton(Dialog)
        self.add.setGeometry(QtCore.QRect(110, 130, 93, 28))
        self.add.setObjectName("add")
        self.dele = QtWidgets.QPushButton(Dialog)
        self.dele.setGeometry(QtCore.QRect(280, 130, 93, 28))
        self.dele.setObjectName("del")
        self.tekst = QtWidgets.QLineEdit(Dialog)
        self.tekst.setGeometry(QtCore.QRect(60, 60, 371, 22))
        self.tekst.setObjectName("tekst")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(190, 20, 201, 21))
        self.label.setObjectName("label")
        self.list = QtWidgets.QListWidget(Dialog)
        self.list.setGeometry(QtCore.QRect(30, 210, 421, 371))
        self.list.setObjectName("list")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.add.setText(_translate("Dialog", "add"))
        self.dele.setText(_translate("Dialog", "del"))
        self.label.setText(_translate("Dialog", "write somethog "))
