# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sliders.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(662, 479)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.sugarhorizontalScrollBar = QtWidgets.QScrollBar(Dialog)
        self.sugarhorizontalScrollBar.setGeometry(QtCore.QRect(280, 50, 321, 20))
        self.sugarhorizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.sugarhorizontalScrollBar.setObjectName("sugarhorizontalScrollBar")

        self.pusleLVLverticalScrollBar = QtWidgets.QScrollBar(Dialog)
        self.pusleLVLverticalScrollBar.setGeometry(QtCore.QRect(200, 170, 20, 191))
        self.pusleLVLverticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.pusleLVLverticalScrollBar.setObjectName("pusleLVLverticalScrollBar")

        self.presyrehorizontalSlider = QtWidgets.QSlider(Dialog)
        self.presyrehorizontalSlider.setGeometry(QtCore.QRect(280, 120, 321, 22))
        self.presyrehorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.presyrehorizontalSlider.setObjectName("presyrehorizontalSlider")

        self.cholesterolLVLverticalSlider = QtWidgets.QSlider(Dialog)
        self.cholesterolLVLverticalSlider.setGeometry(QtCore.QRect(510, 170, 22, 171))
        self.cholesterolLVLverticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.cholesterolLVLverticalSlider.setObjectName("cholesterolLVLverticalSlider")

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(300, 180, 151, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 180, 121, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 131, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 101, 31))
        self.label_4.setObjectName("label_4")

        self.result = QtWidgets.QLineEdit(Dialog)
        self.result.setGeometry(QtCore.QRect(50, 400, 561, 22))
        self.result.setObjectName("result")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "chilesterol level"))
        self.label_2.setText(_translate("Dialog", "pulse level"))
        self.label_3.setText(_translate("Dialog", "blood presure"))
        self.label_4.setText(_translate("Dialog", "sugar level"))
