# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 640)
        self.Bshow = QtWidgets.QPushButton(Dialog)
        self.Bshow.setGeometry(QtCore.QRect(50, 470, 93, 28))
        self.Bshow.setObjectName("Bshow")

        self.LELname = QtWidgets.QLineEdit(Dialog)
        self.LELname.setGeometry(QtCore.QRect(150, 400, 241, 22))
        self.LELname.setObjectName("LELname")

        self.LEname = QtWidgets.QLineEdit(Dialog)
        self.LEname.setGeometry(QtCore.QRect(150, 350, 231, 22))
        self.LEname.setObjectName("LEname")

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 400, 55, 16))
        self.label.setObjectName("label")
        #Bshow Badd Bdel nick LELname LEname list
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 360, 55, 16))
        self.label_2.setObjectName("label_2")

        self.list = QtWidgets.QListWidget(Dialog)
        self.list.setAlternatingRowColors(True)
        self.list.setGeometry(QtCore.QRect(110, 50, 256, 192))
        self.list.setObjectName("list")

        self.Badd = QtWidgets.QPushButton(Dialog)
        self.Badd.setGeometry(QtCore.QRect(280, 560, 93, 28))
        self.Badd.setObjectName("Badd")

        self.Bdel = QtWidgets.QPushButton(Dialog)
        self.Bdel.setGeometry(QtCore.QRect(140, 550, 93, 28))
        self.Bdel.setObjectName("Bdel")

        self.nick = QtWidgets.QLineEdit(Dialog)
        self.nick.setGeometry(QtCore.QRect(300, 480, 113, 22))
        self.nick.setObjectName("nick")

        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(220, 480, 55, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Bshow.setText(_translate("Dialog", "show"))
        self.label.setText(_translate("Dialog", "lastname"))
        self.label_2.setText(_translate("Dialog", "name"))
        self.Badd.setText(_translate("Dialog", "add"))
        self.Bdel.setText(_translate("Dialog", "del"))
        self.label_3.setText(_translate("Dialog", "nick"))
