# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CheckBox2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(591, 390)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(196, 17, 61, 21))
        self.label.setObjectName("label")
        self.labelAmount = QtWidgets.QLabel(Dialog)
        self.labelAmount.setGeometry(QtCore.QRect(160, 340, 250, 33))
        self.labelAmount.setText("")
        self.labelAmount.setObjectName("labelAmount")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(41, 217, 147, 24))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(41, 101, 183, 24))
        self.label_4.setObjectName("label_4")
        self.groupBoxIceCreams_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBoxIceCreams_2.setGeometry(QtCore.QRect(257, 44, 251, 134))
        self.groupBoxIceCreams_2.setObjectName("groupBoxIceCreams_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxIceCreams_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBoxChoclateChips = QtWidgets.QCheckBox(self.groupBoxIceCreams_2)
        self.checkBoxChoclateChips.setObjectName("checkBoxChoclateChips")
        self.verticalLayout_2.addWidget(self.checkBoxChoclateChips)
        self.checkBoxCookieDough = QtWidgets.QCheckBox(self.groupBoxIceCreams_2)
        self.checkBoxCookieDough.setObjectName("checkBoxCookieDough")
        self.verticalLayout_2.addWidget(self.checkBoxCookieDough)
        self.checkBoxChoclateAlmond = QtWidgets.QCheckBox(self.groupBoxIceCreams_2)
        self.checkBoxChoclateAlmond.setObjectName("checkBoxChoclateAlmond")
        self.verticalLayout_2.addWidget(self.checkBoxChoclateAlmond)
        self.checkBoxRockyRoad = QtWidgets.QCheckBox(self.groupBoxIceCreams_2)
        self.checkBoxRockyRoad.setObjectName("checkBoxRockyRoad")
        self.verticalLayout_2.addWidget(self.checkBoxRockyRoad)
        self.groupBoxDrinks = QtWidgets.QGroupBox(Dialog)
        self.groupBoxDrinks.setGeometry(QtCore.QRect(257, 184, 151, 108))
        self.groupBoxDrinks.setObjectName("groupBoxDrinks")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxDrinks)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBoxCoffee = QtWidgets.QCheckBox(self.groupBoxDrinks)
        self.checkBoxCoffee.setObjectName("checkBoxCoffee")
        self.verticalLayout.addWidget(self.checkBoxCoffee)
        self.checkBoxSoda = QtWidgets.QCheckBox(self.groupBoxDrinks)
        self.checkBoxSoda.setObjectName("checkBoxSoda")
        self.verticalLayout.addWidget(self.checkBoxSoda)
        self.checkBoxTea = QtWidgets.QCheckBox(self.groupBoxDrinks)
        self.checkBoxTea.setObjectName("checkBoxTea")
        self.verticalLayout.addWidget(self.checkBoxTea)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Menu"))
        self.label_3.setText(_translate("Dialog", "selest your drink"))
        self.label_4.setText(_translate("Dialog", "select your icecream"))
        self.groupBoxIceCreams_2.setTitle(_translate("Dialog", "Icecerams"))
        self.checkBoxChoclateChips.setText(_translate("Dialog", "Mint Choclate Chips $4"))
        self.checkBoxCookieDough.setText(_translate("Dialog", "Cookie Dough $2"))
        self.checkBoxChoclateAlmond.setText(_translate("Dialog", "Choclate Almond $3"))
        self.checkBoxRockyRoad.setText(_translate("Dialog", "Rocky Road $5"))
        self.groupBoxDrinks.setTitle(_translate("Dialog", "Drinks"))
        self.checkBoxCoffee.setText(_translate("Dialog", "Coffee $2"))
        self.checkBoxSoda.setText(_translate("Dialog", "Soda $3"))
        self.checkBoxTea.setText(_translate("Dialog", "Tea $1 "))
