# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ListWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 640)
        self.listWidgetSelected = QtWidgets.QListWidget(Dialog)
        self.listWidgetSelected.setGeometry(QtCore.QRect(120, 390, 256, 192))
        self.listWidgetSelected.setObjectName("listWidgetSelected")
        self.listWidgetTools = QtWidgets.QListWidget(Dialog)
        self.listWidgetTools.setGeometry(QtCore.QRect(90, 70, 256, 192))
        self.listWidgetTools.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidgetTools.setObjectName("listWidgetTools")
        item = QtWidgets.QListWidgetItem()
        self.listWidgetTools.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetTools.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetTools.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetTools.addItem(item)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 330, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(170, 40, 71, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        __sortingEnabled = self.listWidgetTools.isSortingEnabled()
        self.listWidgetTools.setSortingEnabled(False)
        item = self.listWidgetTools.item(0)
        item.setText(_translate("Dialog", "QTdesigner"))
        item = self.listWidgetTools.item(1)
        item.setText(_translate("Dialog", "JavaDesigner"))
        item = self.listWidgetTools.item(2)
        item.setText(_translate("Dialog", "AndroidDesigner"))
        item = self.listWidgetTools.item(3)
        item.setText(_translate("Dialog", "RadStudio"))
        self.listWidgetTools.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Dialog", "Selecetd tools"))
        self.label_2.setText(_translate("Dialog", "Desig tools"))
